name: Global Check

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: "Global Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3"

      - name: Install Bun Dependencies
        run: bun install

      - name: Check Formatting
        run: bun oxfmt -c .oxfmtrc.json --check .

      - name: Lint
        run: bun oxlint -c .oxlintrc.json

      - name: Check Types
        run: bun ts:check
