name: Global Check

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: "Global Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3"

      - name: Cache and Install Bun Dependencies
        uses: ./.github/actions/cache-deps

      - name: Check Formatting
        run: bun format:check

      - name: Lint
        run: bun lint

      - name: Check Types
        run: bun ts:check
